//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace start_right.Module.BusinessObjects.StartRight
{

    public partial class Gender : XPObject
    {
        string fgender;
        public string gender
        {
            get { return fgender; }
            set { SetPropertyValue<string>(nameof(gender), ref fgender, value); }
        }
        [Association(@"tblStudentReferencesGender")]
        public XPCollection<tblStudent> tblStudents { get { return GetCollection<tblStudent>(nameof(tblStudents)); } }
    }

}
