//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace start_right.Module.BusinessObjects.StartRight
{

    public partial class tblClass : XPLiteObject
    {
        string fclassName;
        [Key]
        public string className
        {
            get { return fclassName; }
            set { SetPropertyValue<string>(nameof(className), ref fclassName, value); }
        }
        Teacher fclassTeacher;
        [Association(@"tblClassReferencesTeacher")]
        public Teacher classTeacher
        {
            get { return fclassTeacher; }
            set { SetPropertyValue<Teacher>(nameof(classTeacher), ref fclassTeacher, value); }
        }
        [Association(@"tblStudentReferencestblClass")]
        public XPCollection<tblStudent> tblStudents { get { return GetCollection<tblStudent>(nameof(tblStudents)); } }
    }

}
