//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace start_right.Module.BusinessObjects.StartRight
{

    public partial class tblSubject : XPObject
    {
        string fsubjectName;
        public string subjectName
        {
            get { return fsubjectName; }
            set { SetPropertyValue<string>(nameof(subjectName), ref fsubjectName, value); }
        }
        Teacher fsubjectTeacher;
        [Association(@"tblSubjectReferencesTeacher")]
        public Teacher subjectTeacher
        {
            get { return fsubjectTeacher; }
            set { SetPropertyValue<Teacher>(nameof(subjectTeacher), ref fsubjectTeacher, value); }
        }
        [Association(@"tblResultReferencestblSubject")]
        public XPCollection<tblResult> tblResults { get { return GetCollection<tblResult>(nameof(tblResults)); } }
    }

}
