//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace start_right.Module.BusinessObjects.StartRight
{

    public partial class tblStudent : XPLiteObject
    {
        string fstdId;
        [Key]
        public string stdId
        {
            get { return fstdId; }
            set { SetPropertyValue<string>(nameof(stdId), ref fstdId, value); }
        }
        string fname;
        public string name
        {
            get { return fname; }
            set { SetPropertyValue<string>(nameof(name), ref fname, value); }
        }
        DateTime fdob;
        public DateTime dob
        {
            get { return fdob; }
            set { SetPropertyValue<DateTime>(nameof(dob), ref fdob, value); }
        }
        Gender fgender;
        [Association(@"tblStudentReferencesGender")]
        public Gender gender
        {
            get { return fgender; }
            set { SetPropertyValue<Gender>(nameof(gender), ref fgender, value); }
        }
        tblClass fclassName;
        [Association(@"tblStudentReferencestblClass")]
        public tblClass className
        {
            get { return fclassName; }
            set { SetPropertyValue<tblClass>(nameof(className), ref fclassName, value); }
        }
        [PersistentAlias("[stdId] + '-' + [name]")]
        public string IdName
        {
            get { return (string)(EvaluateAlias(nameof(IdName))); }
        }
        [Association(@"tblResultReferencestblStudent")]
        public XPCollection<tblResult> tblResults { get { return GetCollection<tblResult>(nameof(tblResults)); } }
    }

}
