//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace start_right.Module.BusinessObjects.StartRight
{

    public partial class Teacher : XPLiteObject
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fContact;
        [Key]
        public string Contact
        {
            get { return fContact; }
            set { SetPropertyValue<string>(nameof(Contact), ref fContact, value); }
        }
        string fEmail;
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>(nameof(Email), ref fEmail, value); }
        }
        decimal fSalary;
        public decimal Salary
        {
            get { return fSalary; }
            set { SetPropertyValue<decimal>(nameof(Salary), ref fSalary, value); }
        }
        [Association(@"tblClassReferencesTeacher")]
        public XPCollection<tblClass> tblClasses { get { return GetCollection<tblClass>(nameof(tblClasses)); } }
        [Association(@"tblSubjectReferencesTeacher")]
        public XPCollection<tblSubject> tblSubjects { get { return GetCollection<tblSubject>(nameof(tblSubjects)); } }
    }

}
